### ISSUE TITLE
Add a day number to the share snippet

### ISSUE THREAD

**Issue by dxxchen** [ryanbarouki/flagle#2]
Since Flagle resets at [midnight local time](https://github.com/ryanbarouki/flagle/blob/main/src/App.js#L111), two people doing Flagle in different time zones at the same time can get different puzzles. Adding a day number would allow people to more easily compare puzzles; for example:

> #Flagle #34 4/6
> 🟩🟥🟩
> 🟥🟥🟩

One way to do this would be to use [`parseInt(DateTime.diff(firstDayOfFlagle, 'days') + 1)`](https://moment.github.io/luxon/api-docs/index.html#:~:text=diff(otherDateTime%2C%20unit%2C%20opts)) to get the number since the first day of Flagle. To avoid misnumbering if someone starts Flagle on one day and finishes on the next, you could pass the date from [`getDayString()`](https://github.com/ryanbarouki/flagle/blob/main/src/App.js#L98) to the share function.

**Comment by ryanbarouki** [comment]
Thanks for the great suggestion! This should now be live.
